# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:18
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_auto_20171029_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='competition'),
        ),
    ]
