# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_auto_20171029_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='startime',
            new_name='starttime',
        ),
    ]
