# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_auto_20180317_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='subscription',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
