# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171029_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='8400 Winterthur', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, default='Marktgasse 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+41791234678', max_length=128, null=True, verbose_name='Natelnummer'),
        ),
    ]
